name: Build & Release

# Sets the trigger to changing the VERSION file in the main branch
on:
  push:
    branches:
    - main
    paths:
    - 'VERSION'

# Allows the workflow to create release
permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: windows-latest
    steps:
    - name: Sync Repo to the Server
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Create Output Directory
      run: New-Item -ItemType Directory -Path .\output

    - name: Build Resources
      run: rc /fo src\resources.res src\resources.rc

    - name: Compile Binary
      run: nmake /f Makefile

    - name: Copy Binary to Output
      run: Copy-Item ProcExpBYOK.exe .\output\ProcExpBYOK.exe

    - name: Read Version
      run: |
        $version = Get-Content VERSION
        Write-Output "VERSION=$version" >> $env:GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: ${{ github.event.repository.name }} ${{ env.VERSION }}
        make_latest: true
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        files: ./output/*